int islower(int a);
int isupper(int a);
int isdigit(int a);
int isalnum(int a);
int isalpha(int a);
int isgraph(int a);
int isblank( int c);
int isxdigit(int a);
char *index(char *s , int c);
char *index(char *s , int c);
char   *strcpy(char *s,char *d);
char   *strncpy(char *s,char *d ,int n);
int astrncat ( char *p , char *a, int n );
