a.out:add_node.c get_right.c get_left.c inorder.c main.c pop.c push.c util.c p_delete.c defs.h psearch.c
	gcc -g add_node.c get_right.c get_left.c inorder.c main.c pop.c push.c util.c p_delete.c psearch.c

clean:
	rm -rf a.out 

