int get_bit_val_by_pos(int n, int bp);
int get_bit_count(int n);
int is_power_of_two(int n);
int get_bit_val_by_pos(int n, int bp);
int show_bits(int n);
int show_bits_range( int n, int spos, int epos );
int x_and_y(int x , int y);
int alloddbits(int n);
int oddbits(int n);
int bit_parity(int n);
int get_byte( int n, int byte_pos);
